spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Mysqlfuck40!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 1440
  refresh-token-expiration-minutes: 20160

mail:
  address:
    admin: admin@email.com

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace